### ISSUE TITLE
Missing padding is not re-added

### ISSUE THREAD

**Issue by Luzifer** [pquerna/otp#10]
Some services like Dropbox, Amazon, Streamtip, Nightbot, … are issuing TOTP secrets whose padding is missing. These TOTP URLs are recognised perfectly fine by Authy or Google Authenticator while this library throws an error: `Decoding of secret as base32 failed.`

Even though this is indeed a broken base32 string it can be fixed very fast and this should be implemented in the library itself to ensure it can use the same secrets as for example Google Authenticator.

**Testcase:**
![download](https://cloud.githubusercontent.com/assets/20142/21660039/edb7f2e8-d2cd-11e6-9246-a7442d330ee0.png)
`otpauth://totp/Example?secret=JBSWY3DPEHPK3PX`

**Required code to fix the missing padding:**
https://play.golang.org/p/5R3qUOTO2a

**Comment by pquerna** [comment]
Fixed by #12
