### ISSUE TITLE
Invalid URL for secret size not divisible by 5

### ISSUE THREAD

**Issue by delicb** [pquerna/otp#15]
When I try to generate totp QR code with secret size that is not divisible by 5 I get error as in attached images. 

Cause of it is that base32 that is used to encode secret adds padding and uses character "=" whenever length of payload to be encoded is not divisible by 5. This can be seen here: https://play.golang.org/p/Uu-iQQYsqr

URL that is generated is escaped and "=" turns into "%3D" which is not valid when it comes to Google authenticator and Authy (I have not tried with other apps).

Example of generated URL is:
```
otpauth://totp/MyIssuer:myUsername?algorithm=SHA512&digits=6&issuer=MyIssuer&period=30&secret=RAAE72RC75YKBVGZ2C35C%3D%3D%3D
```

[RFC3548](https://tools.ietf.org/html/rfc3548#section-2.2) states that payload should be encoded unless the specification referring to 
it document explicitly states otherwise. And in Google authenticator document
about [Key URI format](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#secret) it is stated that padding is not required and should be omitted.

I have only used TOTP, but HOTP has same issue (as quick test reviles).

![Google Authenticator](https://user-images.githubusercontent.com/131180/28495706-16e8af46-6f58-11e7-9c2a-c5cd998aa47d.png)
![Authy](https://user-images.githubusercontent.com/131180/28495707-1d2df8ca-6f58-11e7-9606-7e5286f32ebb.png)

**Comment by pquerna** [comment]
Fixed by #16 -- thank you for the detailed report and pull request
