### ISSUE TITLE
Prevent Conflicting Accounts

### ISSUE THREAD

**Issue by daviian** [pquerna/otp#20]
Google proposes actions mentioned on [Conflicting Accounts](https://github.com/google/google-authenticator/wiki/Conflicting-Accounts) to prevent conflicting accounts with same username on different websites.

I come accross it using [Gitea](https://github.com/go-gitea/gitea) in production and in my local machine for development.
While testing TOTP on my local machine I unfortunately have overwritten my key from production server, thus locking me out of the production system.

Must admit that I am new to TOTP protocol.
Is it something you can implement in your library or is it the reponsibility of the library's user?

**Comment by pquerna** [comment]
hmm.  I think `otp` already exposes everything you need.  On `GenerateOpts`, you have full control over both the Issuer and AccountName fields, which is what Google's wiki page on Conflicting accounts is talking about:

https://godoc.org/github.com/pquerna/otp/totp#GenerateOpts

In Gitea, they could easily change the `AccountName ` name to 
```
AccountName: setting.AppName + ": "+ ctx.User.Name,
```
https://github.com/go-gitea/gitea/blob/f960e19c590d27fe62a3a6241f1ea8b7fadde13a/routers/user/setting.go#L585-L588

**Comment by daviian** [comment]
Thank you for clarification.

I will open an issue in gitea ;-)
