### ISSUE TITLE
Google changed provisioning of totp-URLs to lowercase-base32 now, which fails to parse

### ISSUE THREAD

**Issue by joonas-fi** [pquerna/otp#24]
Google gave me a QR code with this content: `otpauth://totp/Google%3Afoo%40example.com?secret=qlt6vmy6svfx4bt4rpmisaiyol6hihca&issuer=Google` (don't worry, I haven't taken this secret into use).

It yields this error: `Decoding of secret as base32 failed`

If I uppercase the secret myself (=> `otpauth://totp/Google%3Afoo%40example.com?secret=QLT6VMY6SVFX4BT4RPMISAIYOL6HIHCA&issuer=Google`), it succeeds.

**Comment by pquerna** [comment]
hmm.  I guess we can mutate the input;  We already do this for base32 that are missing their padding bytes:

https://github.com/pquerna/otp/blob/c39aab74d8549539a3d7f40a2f5a344adb67cb50/hotp/hotp.go#L73-L83

**Comment by pquerna** [comment]
@joonas-fi Thanks for letting me know about this issue!

**Comment by joonas-fi** [comment]
No problem. I'm using your library in my project (https://github.com/function61/pi-security-module - hugely work-in-progress), so the least I could do is help make an already good library a bit better. :) Awesome work, man, and glad to see you added a test for this case as well!
