### ISSUE TITLE
validate six digits one time password

### ISSUE THREAD

**Issue by zemirco** [pquerna/otp#3]
First of all thank you for this great library!

I'm using otp for my web service and I'm currently trying to write some tests against my login process. Since otp uses six digits by default (same as google authenticator app) I have to create a valid otp with six digits.

I looked at your tests for otp but they all use eight digits. How can I generate a valid six digit one time password?

Thank you!

**Comment by zemirco** [comment]
Found the solution by looking at the tests for `hotp`.

```go
valid, err := totp.ValidateCustom(
	"755224",
	secSha1,
	time.Unix(29, 0),
	totp.ValidateOpts{
		Digits:    otp.DigitsSix,
		Algorithm: otp.AlgorithmSHA1,
	},
)
if err != nil {
	panic(err)
}
```

**Comment by zemirco** [comment]
Sorry I spoke too early :) Was too excited to see that valid was `true`.

I'd like to generate a six digit one time password that is valid now! I mean without passing the time.

**Comment by pquerna** [comment]
@zemirco you mean generate a token like, what a client would supply?  I think that is a dup of #5 really then.

**Comment by cathalgarvey** [comment]
Hey @zemirco, with PR #6 you'd use `totp.GenerateCode(<your_secret>, time.Now())` to generate a valid six-digit code a-la Google Authenticator and friends. Would that suit?

**Comment by zemirco** [comment]
Thank you. That's what I meant.
