### ISSUE TITLE
go mod pulls the old version of the package

### ISSUE THREAD

**Issue by bmdelacruz** [pquerna/otp#34]
Since the latest commit be78767 on the master branch doesn't have a tag, `go mod` pulls the commit b7b8925 (v1.0.0, 9 commits behind). New users of this package, especially those who are using go modules, need to explicitly run `go get github.com/pquerna/otp@master`.

**Comment by pquerna** [comment]
I've tagged v1.1.0 to fix this:
https://github.com/pquerna/otp/releases/tag/v1.1.0

Frankly the `go mod` defaults don't fit my lifestyle, but this is the direction the community is going... so trying not to swim upstream too much here.  If you run into any issues please let me know,

Cheers,

Paul
