### ISSUE TITLE
Hiding Code Generation Makes Testing Hard

### ISSUE THREAD

**Issue by cathalgarvey** [pquerna/otp#5]
Hey @pquerna, thanks for this library! I'm currently reimplementing a security system from Python in Go that uses TOTP to control access to a physical location, and it's great to have a sane interface for validating codes.

The problem though, is that this library is *only* for server-side authentication and not for client-side authcode generation. This seems like a missed opportunity generally, but specifically it makes testing very awkward. I'd like to be able to generate a few keys for testing, then run my system through its paces using these keys, but the interface expects that external code will do the code generation.

Any way you could add a pair of generator methods to `totp.Key`, such as `CodeFromCounter(i int) string` and `CodeFromTime(t time.Time) string`, for testing and client generation uses?

Thanks!

**Comment by pquerna** [comment]
I'd be happy to merge a PR with the methods you suggest :)

**Comment by cathalgarvey** [comment]
Cool, will look at writing something later, thanks!
