### ISSUE TITLE
Prevent re-use of TOTP code

### ISSUE THREAD

**Issue by BirknerAlex** [pquerna/otp#61]
Hey, 

just wondering if the library supports passing the last_used timestamp `time.Time` to the TOTP validation. Since these are "one-time" codes its really important that each code can be used only one time otherwise an attacker would be able to login with the same token (if stolen) on the account.

I was using a Ruby backend before and there was a option for it:
https://github.com/mdp/rotp/blob/62874be71d74380d252c73409dd81da08b021497/lib/rotp/totp.rb#L39

Is there any way to archive this with this project?

Thanks in advance!

Alex

**Comment by pquerna** [comment]
I think this is outside the scope of this library and firmly in the scope of an application concern - storing previously used OTPs requires a datastore like redis/mysql/etc which is not something I think this library should depend upon - and its just a simple lookup if a TOTP has been used within the last few minutes.
