### ISSUE TITLE
Problems with example code and google authenticator (android)

### ISSUE THREAD

**Issue by Pranav-B23** [pquerna/otp#63]
Hello,
So I was trying out the library and using google authenticator to scan the QR codes. This is the code I'm using to do so.

	import (
		"github.com/pquerna/otp"
		"github.com/pquerna/otp/totp"

		"bufio"
		"bytes"
		"fmt"
		"image/png"
		"io/ioutil"
		"os"
	)

	func display(key *otp.Key, data []byte) {
		fmt.Printf("Issuer:       %s\n", key.Issuer())
		fmt.Printf("Account Name: %s\n", key.AccountName())
		fmt.Printf("Secret:       %s\n", key.Secret())
		fmt.Printf("URL:          %s\n", key.URL())
		fmt.Println("Writing PNG to qr-code.png....")
		ioutil.WriteFile("qr-code.png", data, 0644)
		fmt.Println("")
		fmt.Println("Please add your TOTP to your OTP Application now!")
		fmt.Println("")
	}

	func promptForPasscode() string {
		reader := bufio.NewReader(os.Stdin)
		fmt.Print("Enter Passcode: ")
		text, _ := reader.ReadString('\n')
		return text
	}

	func main() {
		key, err := totp.Generate(totp.GenerateOpts{
			Issuer:      "Example.com",
			AccountName: "alice@example.com",
			Algorithm:   otp.AlgorithmSHA1,
		})
		if err != nil {
			panic(err)
		}
		// Convert TOTP key into a PNG
		var buf bytes.Buffer
		img, err := key.Image(200, 200)
		if err != nil {
			panic(err)
		}
		png.Encode(&buf, img)

		// display the QR code to the user.
		display(key, buf.Bytes())

		// Now Validate that the user's successfully added the passcode.
		fmt.Println("Validating TOTP...")
		for {
			passcode := promptForPasscode()
			valid := totp.Validate(passcode, key.Secret())
			if valid {
				println("Valid passcode!")
			} else {
				println("Invalid passocde!")
			}
		}
	}

This generates a QR code which I am able to scan with goole authenticator, but everytime i try the passcode it is invalid. Wanted to know if theres some issue with my code.

**Comment by SaTae66** [comment]
Have you been able to get it working? 
If not:
Works fine for me. Are you entering the passcode WITH the space in between the 1. three digits and the 2. three digits?

**Comment by valichek** [comment]
Hi, I have more-less same issue. Code from `GenerateCodeCustom()` works, but code from Google Authenticator doesn't.

**Comment by JimBeam2019** [comment]
Hi @Pranav-B23 , have you been able to solve it? I've tried your code with Google Authenticator and I have the same problem as what you had.

**Comment by atacirus** [comment]
Hi all, I saw the same when the clock time on my computer was not correctly set (2min off). Synchronizing the clock resolved the issue.

**Comment by lemonScaletech** [comment]
I am facing this issue with google authenticator, getting inavlid passcode error.
Previously I was trying custom validation still faced the issue. Now doing it basic way still getting the issue. 
I am attaching the code, can you please let me know what I am doing wrong ?

`package main

import (
	"bufio"
	"bytes"
	"encoding/base64"
	"fmt"
	"image/png"
	"io/ioutil"
	"os"

        "github.com/pquerna/otp"
	"github.com/pquerna/otp/totp"
)

func main() {
	key, err := totp.Generate(totp.GenerateOpts{
		Issuer:      "google.com",
		AccountName: "anand@gmail.com",
	})
	if err != nil {
		panic(err)
	}
	// Convert TOTP key into a PNG
	var buf bytes.Buffer
	img, err := key.Image(200, 200)
	if err != nil {
		panic(err)
	}
	png.Encode(&buf, img)
	encodedText := base64.StdEncoding.EncodeToString(buf.Bytes())
	fmt.Println("\n", encodedText)
	// display the QR code to the user.
	display(key, buf.Bytes())

	// Now Validate that the user's successfully added the passcode.
	fmt.Println("Validating TOTP...")
	passcode := promptForPasscode()
	//otp.NewKeyFromURL(
	valid := totp.Validate(passcode, key.Secret())
	if valid {
		println("Valid passcode!")
		os.Exit(0)
	} else {
		println("Invalid passcode!")
		os.Exit(1)
	}
}

func display(key *otp.Key, data []byte) {
	fmt.Printf("Issuer:       %s\n", key.Issuer())
	fmt.Printf("Account Name: %s\n", key.AccountName())
	fmt.Printf("Secret:       %s\n", key.Secret())
	fmt.Println("Writing PNG to qr-code.png....")
	ioutil.WriteFile("qr-code.png", data, 0644)
	fmt.Println("")
	fmt.Println("Please add your TOTP to your OTP Application now!")
	fmt.Println("")
}

func promptForPasscode() string {
	reader := bufio.NewReader(os.Stdin)
	fmt.Print("Enter Passcode: ")
	text, _ := reader.ReadString('\n')
	return text
}
`
