### ISSUE TITLE
Feature request: 4 digits OTP

### ISSUE THREAD

**Issue by AlexDede** [pquerna/otp#7]
Can you add support 4 digits OTP?

Thanks!

**Comment by reginaldosousa** [comment]
I also need this feature, but with 10 digits.

**Comment by pquerna** [comment]
The simple patch is about 3 lines, one for the const entry, and two for the fmt string.  Not sure its ideal, but I don't know how many other digit types there will be.

If you don't mind sharing, I've not seen a 10 digit OTP in the wild, is there mobile client generating these?

**Comment by pquerna** [comment]
I see @reginaldosousa branch:

https://github.com/pquerna/otp/compare/master...reginaldosousa:allow-any-number-of-digits

Would be happy to merge that as is....

**Comment by reginaldosousa** [comment]
In my company we use TOTP both SMS validation as to generate an activation code that is sent by email. This activation code has 10 digits.

It would be great if you could merge my branch.
I need to open a pull request?

**Comment by pquerna** [comment]
Yeah, pull request would be great!

**Comment by pquerna** [comment]
Fixed by #8
