### ISSUE TITLE
invalid code

### ISSUE THREAD

**Issue by kimycai** [pquerna/otp#79]
![image](https://user-images.githubusercontent.com/17998728/221463955-080414cb-592d-40b7-80a0-799d615b924a.png)
It shows "Invalid 2FA Code" after first time Enter in Alist login, but second time Enter will be OK.

**Comment by urielbz** [comment]
Same problem here! any solution!?

**Comment by urielbz** [comment]
> Same problem here! any solution!?

For now, we have simulate the first code generator, secret key and validation and then we do geneerate the real code and send it. seems to work for now. If there any better solution will love to hear it

**Comment by pquerna** [comment]
Not enough information here to debug whats going on;  I suggest contacting Alist?
